# Use official node image as the base image
FROM node:20-slim

# Set /app directory as default working directory
WORKDIR /usr/src/frontend

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies
RUN npm install

# Expose port 8080
EXPOSE 8080

# Serve the app
CMD [ "npm", "run" ,"dev"]
