version: "3.8"

services:
  frontend:
    container_name: mern-frontend
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.prod
    environment:
      EXPRESS_HOST: backend
      NODE_ENV: production
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - backend

  backend:
    container_name: mern-backend
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.prod
    networks:
      - default
      - frontend
    ports:
      - "3000:3000"
    env_file: ./backend/.env
    environment:
      NODE_ENV: production
    restart: always
    depends_on:
      - mongo

  mongo:
    container_name: mern-mongo
    image: mongo:latest
    networks:
      - default
    ports:
      - "27017:27017"
    volumes:
      - ./backend/docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=mern_boilerplate
      - MONGO_INITDB_USER=mongo_user
      - MONGO_INITDB_PASSWORD=Password123

volumes:
  mongo-data:

networks:
  default:
    name: mern-backend
  frontend:
    name: mern-frontend