version: "3.8"

services:
  frontend:
    container_name: mern_frontend_dev
    build:
      context: ./frontend
      dockerfile: docker/Dockerfile.dev
    environment:
      EXPRESS_HOST: backend
      NODE_ENV: development
    networks:
      - frontend_dev
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules
    # https://github.com/facebook/create-react-app/issues/8688
    stdin_open: true
    restart: always
    depends_on:
      - backend

  backend:
    container_name: mern_backend_dev
    build:
      context: ./backend
      dockerfile: docker/Dockerfile.dev
    networks:
      - default_dev
      - frontend_dev
    ports:
      - "3001:3000"
    env_file: ./backend/.env
    environment:
      NODE_ENV: development
    volumes:
      - ./backend:/usr/src/backend
      - /usr/src/backend/node_modules
    restart: always
    depends_on:
      - mongo

  mongo:
    container_name: mern_mongo_dev
    image: mongo:latest
    networks:
      - default_dev
    ports:
      - "27018:27017"
    volumes:
      - ./backend/docker/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongo-data:/data/db
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=mern_boilerplate
      - MONGO_INITDB_USER=mongo_user
      - MONGO_INITDB_PASSWORD=Password123

volumes:
  mongo-data:

networks:
  default_dev:
    name: mern_backend_dev
  frontend_dev:
    name: mern_frontend_dev