# Use official node image as the base image
FROM node:20-slim

# Set /app directory as default working directory
WORKDIR /usr/src/backend

# Copy package.json and package-lock.json
COPY package*.json ./

ENV NODE_ENV=development

# Install all dependencies
RUN npm install

# Copy all files from current directory to /app on the image
COPY . .

# Expose port 5000
EXPOSE 3000

# Run the application
CMD [ "npm", "run" ,"dev" ]
